### ISSUE TITLE
Default Keyboard Shortcut Conflict

### ISSUE THREAD

**Issue by jeremylivingston** [newgiin/cloudplayer-scrobbler#15]
The default "Go to Google Play tab" (cmd+shift+4) currently conflicts with OS X's shortcut to take a screenshot of an area on the screen. Additionally, the cmd+shift+3 shortcut conflicts with OS X's "capture screenshot to file" shortcut.

Should these keyboard shortcuts be changed to remove the requirement of changing them out-of-the-box?

**Comment by larkin** [comment]
Just +1 here, I'd stopped using chrome for a bit so didn't notice this (despite it randomly opening chrome every time I took a screenshot), and when I switched back to chrome and tried to screenshot something this was incredibly painful.  Took me longer than I'd like to figure out how to remap it.

**Comment by newgiin** [comment]
Sorry I didn't update this earlier. The shortcuts have been updated to Ctrl+Shift+{7,8,9,0} for previous_song, toggle_play, next_song, goto_play_tab respectively. It won't update your shortcuts unless you reinstall the extension however, so you're current shortcuts will stay the same. 

PS If you're wondering why the defaults have to be Ctrl+Shift+[0-9], it's because global shortcuts have to be per the "Scope" section in this doc https://developer.chrome.com/extensions/commands#usage

ab0a34f609c942546121387b1c239fb05d426b87

**Comment by larkin** [comment]
Thanks for the update!
