### ISSUE TITLE
Album name isn't scrobbled properly

### ISSUE THREAD

**Issue by codysherman** [newgiin/cloudplayer-scrobbler#4]
The plugin doesn't send the album title to last.fm when scrobbling. This was understandable in the old version of Google Music because it didn't show the album name in the Now Playing bar, but in the new version that information is there, so scraping it and pushing with the scrobble should be as simple as the title and artist. At least I think this is all true, hopefully it's not too hard for you guys!

**Comment by newgiin** [comment]
Hi Cody, what version of the scrobbler are you using (you can check at chrome://extensions)? If you can see the album name in the extension dropdown, it should be scrobbling it, since they use the same field.

How are you determining if the album was scrobbled? It seems in the "Recently listened tracks" list, it will only show the album if you listen to two songs of the same album consecutively. See my history at http://www.last.fm/user/andruun/tracks, all the recent scrobbles are scrobbled from the extension. The albums are there, except for songs where it wasn't followed or preceded by a song from the same album.

**Comment by codysherman** [comment]
Hmmm yes my apologies, I was mistaken because it was showing me the artist images instead of album images. I see that consecutive album songs switch the art from the artist to the album now. Thanks!
