### ISSUE TITLE
Causes Last.fm to throw errors on attempt to authorize

### ISSUE THREAD

**Issue by evano** [newgiin/cloudplayer-scrobbler#5]
The extension has worked great for me for a long time. Since switching to Chrome Canary (32.0.1666.0) it will not authorize on Last.fm. When I click on the "Connect to Last.fm" link in the popup box, I get navigated to Last.fm which lets me log in. But after clicking the "Yes Allow Access" button, an error shows in the console and the page neither connects nor fails. Error is:

Denying load of chrome-extension://llpepekkleeoeiloijhcafgpjdnhhcbl/html/lastfm_callback.html?token=8eda9704746351ce7de9880a241f1f14. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension. auth?api_key=d00dce85051b7dbcbfcc165eaebfc6d2&cb=chrome-extension%3A%2F%2Fllpepekkleeoeiloijhcafgpj…:1

**Comment by newgiin** [comment]
Just pushed version 1.4.8 out that should fix this. I was surprised your issue didn't showup in the default version of Chrome, thanks for reporting it.

Though as an aside, Chrome Canary, being an experimental browser, seems to have a few issues not present in the stable version of Chrome. It ignores the "Artist - Title" scrolling speed in the extension popup so that may still look funny for you. Also, I had an issue before where pressing the extension icon occasionally wouldn't show the popup. The former issue I know is an issue with Canary, though the latter I can't figure out, but I suspect it's just an issue with Canary.
